---
- name: add ppa
  apt_repository:
    repo: 'ppa:chris-lea/uwsgi'
    update_cache: yes
    state: present
  sudo: yes

- name: install uwsgi
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - uwsgi
    - uwsgi-plugin-python
  sudo: yes

- name: install config file
  template:
    src: "{{ uwsgi_app_config }}"
    dest: /etc/uwsgi/apps-available/{{ uwsgi_app_name }}.ini
  notify:
    - restart uwsgi
  sudo: yes

- name: enable app config
  file:
    src: /etc/uwsgi/apps-available/{{ uwsgi_app_name }}.ini
    dest: /etc/uwsgi/apps-enabled/{{ uwsgi_app_name }}.ini
    state: link
  notify:
    - restart uwsgi
  sudo: yes
